<?php 

return [

    'default' => 'test',

    'connections' => [
        'TCRLS01' => [
            'host'      => env('TCRLS01'),
            'hostName' => 'TCRLS01',
            'username'  => env('SMSC_USER_LS'),
            'password'  => env('SMSC_PASSWORD_LS'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],

        'TCRLS02' => [
            'host'      => env('TCRLS02'),
            'hostName' => 'TCRLS02',
            'username'  => env('SMSC_USER_LS'),
            'password'  => env('SMSC_PASSWORD_LS'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],

        'TCRLS03' => [
            'host'      => env('TCRLS03'),
            'hostName' => 'TCRLS03',
            'username'  => env('SMSC_USER_LS'),
            'password'  => env('SMSC_PASSWORD_LS'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],

         'TCRLS04' => [
            'host'      => env('TCRLS04'),
            'hostName' => 'TCRLS04',
            'username'  => env('SMSC_USER_LS'),
            'password'  => env('SMSC_PASSWORD_LS'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],
        'AGWLS01' => [
            'host'      => env('AGWLS01'),
            'hostName' => 'AGWLS01',
            'username'  => env('SMSC_USER_LS'),
            'password'  => env('SMSC_PASSWORD_LS'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],
        'AGWLS02' => [
            'host'      => env('AGWLS02'),
            'hostName' => 'AGWLS02',
            'username'  => env('SMSC_USER_LS'),
            'password'  => env('SMSC_PASSWORD_LS'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],
        'TCRFL01' => [
            'host'      => env('TCRFL01'),
            'hostName' => 'TCRFL01',
            'username'  => env('SMSC_USER_FL'),
            'password'  => env('SMSC_PASSWORD_FL'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],
        'TCRFL02' => [
            'host'      => env('TCRFL02'),
            'hostName' => 'TCRFL02',
            'username'  => env('SMSC_USER_FL'),
            'password'  => env('SMSC_PASSWORD_FL'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],
        'TCRFL03' => [
            'host'      => env('TCRFL03'),
            'hostName' => 'TCRFL03',
            'username'  => env('SMSC_USER_FL'),
            'password'  => env('SMSC_PASSWORD_FL'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],
        'TCRFL04' => [
            'host'      => env('TCRFL04'),
            'hostName' => 'TCRFL04',
            'username'  => env('SMSC_USER_FL'),
            'password'  => env('SMSC_PASSWORD_FL'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],
        'AGWFL01' => [
            'host'      => env('AGWFL01'),
            'hostName' => 'AGWFL01',
            'username'  => env('SMSC_USER_FL'),
            'password'  => env('SMSC_PASSWORD_FL'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],
        'AGWFL02' => [
            'host'      => env('AGWFL02'),
            'hostName' => 'AGWFL02',
            'username'  => env('SMSC_USER_FL'),
            'password'  => env('SMSC_PASSWORD_FL'),
            'key'       => env('PRIVATE_SSH_KEY'),
            'keytext'   => '',
            'keyphrase' => '',
            'agent'     => '',
            'timeout'   => 10,
        ],

    ],
];
